apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deploy
spec:
  replicas: 1
  selector:
     matchLabels:
       app: flask-deploy
  template:
    metadata:
      labels:
        app: flask-deploy
    spec:
      containers:
        - name: flask-pod
          image: docker.io/sysadminsystems/api-flask-kubernetes:alpha
          #imagePullPolicy: "IfNotPresent"
          #command: ["gunicorn --bind 0.0.0.0:5000 manage:app"]
          resources:
            limits:
              memory: "1Gi"
              cpu: "100m"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: FLASK_APP
              value: project/__init__.py
            - name: FLASK_ENV
              value: production
          ports:
            - containerPort: 5000
              name: api-flask
