version: '3.7'

services:
  web:
    build: ./services/web
    image: sysadminsystems/api-flask-kubernetes
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes: 
      - ./services/web/:/usr/src/app/
    expose:
      - 5000
    #ports:
    #  - 5000:5000
    env_file: 
      - ./env.prod
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on: 
      - web
  